### ISSUE TITLE
[Feature Request] Possible to add user-agent "ddclient"?

### ISSUE THREAD

**Issue by credomane** [martinp/ipd#16]
Would it be possible to add the ddclient user-agent to the code?

It sends this for the user-agent ```ddclient/X.X.X``` where X.X.X is the version of ddclient.
ddclient, however, appears to properly parse through the html and get the proper IP address. I figured it would save bandwidth if the IP was given directly without any surrounding html. Much like the response to ```curl ifconfig.co``` is.

**Comment by martinp** [comment]
Sure, I can add support for ddclient.
