### ISSUE TITLE
Certificate Common Name Invalid v6 Domain

### ISSUE THREAD

**Issue by agoodkind** [martinp/ipd#18]
The certificate on the v6 domain's common name mismatches and therefore breaks HSTS and disallows the site to load in Chrome.

![2016-06-12 23_02_51-greenshot](https://cloud.githubusercontent.com/assets/1017680/15996087/d26c9d5a-30f1-11e6-826b-cf6e6d515532.png)

**Comment by martinp** [comment]
This happens because Lets Encrypt does not support IPv6 only hostnames, see https://github.com/martinp/ipd/issues/15.

However, HSTS should be disabled for the v6.ifconfig.co vhost, I'll look into that.

**Comment by martinp** [comment]
Fixed:
```
$ curl -v v6.ifconfig.co
* Rebuilt URL to: v6.ifconfig.co/
* Hostname was NOT found in DNS cache
*   Trying 2001:16d8:ee03::cafe:d00d...
* Connected to v6.ifconfig.co (2001:16d8:ee03::cafe:d00d) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.38.0
> Host: v6.ifconfig.co
> Accept: */*
>
< HTTP/1.1 200 OK
* Server nginx is not blacklisted
< Server: nginx
< Date: Thu, 23 Jun 2016 18:28:59 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 24
< Connection: keep-alive
< Vary: Accept-Encoding
<
2001:700:b00:1800::10:1
* Connection #0 to host v6.ifconfig.co left intact
```
