### ISSUE TITLE
v6.ifconfig.co

### ISSUE THREAD

**Issue by gema-arta** [martinp/ipd#21]
> Chain issues 	Incorrect order, Extra certs, Contains anchor
> Common names 	tar.io   MISMATCH
> Alternative names 	atbapi.tar.io git.tar.io tar.io
> Trusted 	No   NOT TRUSTED

[SSLlabs SSL Report: v6.ifconfig.co (2001:16d8:ee03:0:0:0:cafe:d00d)](https://www.ssllabs.com/ssltest/analyze.html?d=v6.ifconfig.co)

```
$ curl -vvk https://v6.ifconfig.co
* STATE: INIT => CONNECT handle 0x600057790; line 1402 (connection #-5000)
* Rebuilt URL to: https://v6.ifconfig.co/
* Added connection 0. The cache now contains 1 members
*   Trying 2001:16d8:ee03::cafe:d00d...
* STATE: CONNECT => WAITCONNECT handle 0x600057790; line 1455 (connection #0)
* Connected to v6.ifconfig.co (2001:16d8:ee03::cafe:d00d) port 443 (#0)
* STATE: WAITCONNECT => SENDPROTOCONNECT handle 0x600057790; line 1562 (connection #0)
* ALPN, offering h2
* ALPN, offering http/1.1

```

```
   "status": 404,
   "message": "route not found"
 * STATE: PERFORM => DONE handle 0x600057790; line 1955 (connection #0)
 * multi_done
 * Connection #0 to host v6.ifconfig.co left intact
```

**Comment by k0nsl** [comment]
Yes? It looks like somebody was careless with HSTS?

**Comment by gema-arta** [comment]
[https://v6.ifconfig.co/](https://v6.ifconfig.co/)

> Unable to communicate securely with peer: requested domain name does not match the server’s certificate. 
> HTTP Strict Transport Security: true 
> HTTP Public Key Pinning: false 

> v6.ifconfig.co uses an invalid security certificate. 
> The certificate is only valid for the following names: atbapi.tar.io, git.tar.io, tar.io
> Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by gema-arta** [comment]
@k0nsl 

```
$ curl -sik https://v6.ifconfig.co
HTTP/1.1 404 Not Found
Server: nginx
Date: Thu, 14 Jul 2016 20:11:32 GMT
Content-Type: application/json
Content-Length: 51
Connection: keep-alive
Vary: Accept-Encoding
Access-Control-Allow-Methods: GET
Access-Control-Allow-Origin: *

{
  "status": 404,
  "message": "route not found"
}

```

**Comment by martinp** [comment]
HTTPS is not supported for v6.ifconfig.co. Please see #15 and #18.

**Comment by gema-arta** [comment]
But  ```HSTS Preloading	Chrome  Edge  Firefox  IE    Not in: Tor ```
of `SSLlabs SSL Report` in `2001:16d8:ee03::cafe:d00d` aka `ifconfig.co`
create this torouble
@k0nsl assertion partly true
enough to force a single request http to https routes inside the browser

**Comment by martinp** [comment]
@gema-arta Yes, HSTS was mistakenly turned on in the past, and it is on for ifconfig.co, but not for v6.ifconfig.co.

**Comment by martinp** [comment]
I found one problem. The vhost for ifconfig.co was incorrectly adding `includeSubdomains` in the HSTS header, causing HSTS to be enabled for v6.ifconfig.co as well. This has now been fixed.

Before:
`Strict-Transport-Security: max-age=31536000; includeSubdomains; preload``

After:
`Strict-Transport-Security: max-age=31536000; preload`
