### ISSUE TITLE
Should get a "bare" response if you Accept: text/plain

### ISSUE THREAD

**Issue by 00dani** [martinp/ipd#24]
Currently, a request to `GET /` can either give you just your IP address as simple text, or a fancy HTML page - and this decision is exclusively made based on whether your user agent is one of the few recognised by the server as being not-a-browser.

I believe it would be more correct, and more flexible, to support the Accept header when making this decision. In particular, if you only `Accept: text/plain`, then you should naturally get the plain-text response rather than the fancy HTML. In other words, I would expect the following behaviour. (I've omitted all headers that aren't relevant to this issue. :wink: )
```http
GET / HTTP/1.1
Accept: */*
User-Agent: something unrecognised

HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8

<!-- full fancy html page here -->
```
```http
GET / HTTP/1.1
Accept: text/plain
User-Agent: something unrecognised

HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8

127.0.0.1
```
This behaviour is also consistent with the existing support for the Accept header, which allows you to retrieve the JSON response from `GET /` by indicating that you will only `Accept: application/json`.

The existing system which sniffs your user agent would remain in place - although it *would* make sense to override the user agent and give the HTML page to Curl and friends too, if they send `Accept: text/html` rather than the default `Accept: */*`.

**Comment by martinp** [comment]
I agree. Feel free to submit a PR if you want, I think this should be an easy change.
